# Generated by Django 3.2.14 on 2022-07-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blogpost_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='userid',
            new_name='userId',
        ),
    ]
