# Generated by Django 3.2.14 on 2022-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_userid_blogpost_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='userId',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
