# Generated by Django 3.2.14 on 2022-07-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='userId',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
